services:
  - type: web
    name: flask-schools-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn wsgi:app  # Используем python -m
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: RENDER_DISABLE_UV  # ← Ключевая настройка!
        value: true

  - type: postgres
    name: school-db
    plan: free
    ipAllowList: []